plugins {
    id 'java'
    id 'fabric-loom' version '1.10.5'
}

group = 'me.vibing'
version = mod_version

repositories {
    mavenCentral()
}

base {
    archivesName = "${mod_id}-fabric-1.20-1.21.11"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

sourceSets.main.java.setSrcDirs([
        rootProject.file('../core/src/main/java'),
        rootProject.file('../shared-fabric-legacy/src/main/java')])
sourceSets.main.resources.setSrcDirs([
        rootProject.file('../shared-legacy/src/main/resources'),
        file('src/main/resources')])

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings "net.fabricmc:yarn:1.20+build.1:v2"
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
}

loom {
    runs {
        server {
            server()
            runDir 'run'
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}

processResources {
    inputs.properties(mod_id: mod_id, mod_name: mod_name, mod_version: mod_version)
    filesMatching('fabric.mod.json') {
        expand(mod_id: mod_id, mod_name: mod_name, mod_version: mod_version)
    }
}
