plugins {
    id 'java'
    id 'net.minecraftforge.gradle'
}

base {
    archivesName = "${mod_id}-forge-1.20.6-26.2"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

sourceSets.main.java.setSrcDirs([
        rootProject.file('core/src/main/java'),
        rootProject.file('shared/src/main/java'),
        file('src/main/java')])
sourceSets.main.resources.setSrcDirs([
        rootProject.file('shared/src/main/resources'),
        file('src/main/resources')])

minecraft {
    runs {
        register('server') {
            workingDir = layout.projectDirectory.dir('run')
            args '--nogui', "--mixin.config=${mod_id}.mixins.json"
        }
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${forge_version}")
    annotationProcessor 'org.spongepowered:mixin:0.8.7:processor'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}
tasks.named('compileJava', JavaCompile) {
    dependsOn tasks.named('processResources')
    outputs.cacheIf { false }
}

tasks.named('jar', Jar) {
    manifest {
        attributes 'MixinConfigs': "${mod_id}.mixins.json"
    }
}

processResources {
    inputs.properties(
            mod_id: mod_id,
            mod_name: mod_name,
            mod_version: mod_version)
    filesMatching('META-INF/mods.toml') {
        expand(
                mod_id: mod_id,
                mod_name: mod_name,
                mod_version: mod_version)
    }
}
