plugins {
    id 'java'
    id 'net.neoforged.moddev'
}

base {
    archivesName = "${mod_id}-neoforge-1.20.5-26.2"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

sourceSets.main.java.setSrcDirs([
        rootProject.file('core/src/main/java'),
        rootProject.file('shared/src/main/java'),
        file('src/main/java')])
sourceSets.main.resources.setSrcDirs([
        rootProject.file('shared/src/main/resources'),
        file('src/main/resources')])

neoForge {
    version = neoforge_version
    runs {
        server {
            server()
            gameDirectory = file('run')
            programArgument '--nogui'
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

processResources {
    inputs.properties(
            mod_id: mod_id,
            mod_name: mod_name,
            mod_version: mod_version)
    filesMatching('META-INF/neoforge.mods.toml') {
        expand(
                mod_id: mod_id,
                mod_name: mod_name,
                mod_version: mod_version)
    }
}
